name: CI - Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    name: Quality Check (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installazione HTMLHint
      - name: Install htmlhint
        run: |
          npm install -g htmlhint

      # Linting HTML
      - name: Run HTMLHint
        run: |
          htmlhint "**/*.html"

      # Link Checker
      - name: Broken Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress ./ 
